package com.example.matching.agent.json;

import com.example.matching.agent.dto.person.PersonAbilityExtractionResult;
import com.example.matching.agent.lc4j.EmployeeAbilityAiService;
import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.SystemMessage;
import dev.langchain4j.model.chat.Capability;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.request.ResponseFormat;
import dev.langchain4j.model.chat.request.json.JsonObjectSchema;
import dev.langchain4j.model.chat.request.json.JsonSchema;
import dev.langchain4j.model.chat.response.ChatResponse;
import dev.langchain4j.service.AiServices;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;

/**
 * 临时探针测试（Task 14）：观察 langchain4j 1.18.1 AiServices 对返回 POJO 的方法
 * 是否自动生成 JSON schema 及具体内容，供 DTO 注解决策使用。可保留。
 */
class SchemaProbeTest {

    /** 记录收到的 ChatRequest 并返回固定合法 JSON 的录制模型。 */
    static class RecordingModel implements ChatModel {
        final AtomicReference<ChatRequest> lastRequest = new AtomicReference<>();
        final String responseJson;

        RecordingModel(String responseJson) {
            this.responseJson = responseJson;
        }

        @Override
        public ChatResponse chat(ChatRequest request) {
            lastRequest.set(request);
            return ChatResponse.builder().aiMessage(AiMessage.from(responseJson)).build();
        }

        @Override
        public Set<Capability> supportedCapabilities() {
            return Set.of(Capability.RESPONSE_FORMAT_JSON_SCHEMA);
        }
    }

    private static void dumpSchema(String tag, ChatRequest request) {
        if (request == null) {
            System.out.println("[PROBE][" + tag + "] NO REQUEST RECORDED");
            return;
        }
        ResponseFormat rf = request.responseFormat();
        System.out.println("[PROBE][" + tag + "] responseFormat = " + rf);
        if (rf != null && rf.jsonSchema() != null) {
            JsonSchema schema = rf.jsonSchema();
            System.out.println("[PROBE][" + tag + "] jsonSchema.name = " + schema.name());
            if (schema.rootElement() instanceof JsonObjectSchema obj) {
                System.out.println("[PROBE][" + tag + "] jsonSchema.properties = " + obj.properties().keySet());
                System.out.println("[PROBE][" + tag + "] jsonSchema.required   = " + obj.required());
                for (var e : obj.properties().entrySet()) {
                    System.out.println("[PROBE][" + tag + "]   property[" + e.getKey() + "] = " + e.getValue());
                }
            } else {
                System.out.println("[PROBE][" + tag + "] jsonSchema.rootElement = " + schema.rootElement());
            }
        }
    }

    private static final String MINIMAL_JSON = "{\"claims\":[],\"summary\":\"probe\",\"fallbackUsed\":false}";

    /** 探针 1：AiServices 对返回 POJO 的同步方法是否自动生成 schema，内容是什么。 */
    @Test
    void probeAiServicesAutoGeneratedSchema() {
        RecordingModel model = new RecordingModel(MINIMAL_JSON);
        EmployeeAbilityAiService service = AiServices.builder(EmployeeAbilityAiService.class)
                .chatModel(model)
                .build();
        try {
            PersonAbilityExtractionResult result = service.extractAbilities("{\"sourceText\":\"probe\"}");
            System.out.println("[PROBE] call succeeded, claims="
                    + (result != null && result.getClaims() != null ? result.getClaims().size() : "null"));
        } catch (Throwable t) {
            System.out.println("[PROBE] call threw: " + t);
        }
        dumpSchema("aiServices-generated", model.lastRequest.get());
    }

    /** 探针 2：经 JsonGuardChatModel 链路后，AiServices 生成的 responseFormat 是否被保留。 */
    @Test
    void probeJsonGuardPreservesAiServicesSchema() {
        RecordingModel delegate = new RecordingModel(MINIMAL_JSON);
        JsonGuardChatModel guard = new JsonGuardChatModel(delegate, new CapabilityProbe(), new JsonRetryPolicy(2, 1));
        EmployeeAbilityAiService service = AiServices.builder(EmployeeAbilityAiService.class)
                .chatModel(guard)
                .build();
        try {
            service.extractAbilities("{\"sourceText\":\"probe\"}");
        } catch (Throwable t) {
            System.out.println("[PROBE] guard-chain call threw: " + t);
        }
        dumpSchema("after-json-guard", delegate.lastRequest.get());
    }

    /** 探针 3：ChatRequest 已预设 responseFormat（模拟 JsonGuard 注入后）时，delegate 收到的是否仍为预设值。 */
    @Test
    void probePresetResponseFormatReachesDelegate() {
        RecordingModel delegate = new RecordingModel(MINIMAL_JSON);
        JsonGuardChatModel guard = new JsonGuardChatModel(delegate, new CapabilityProbe(), new JsonRetryPolicy(2, 1));
        ChatRequest preset = ChatRequest.builder()
                .messages(List.of(SystemMessage.systemMessage("x")))
                .responseFormat(ResponseFormat.JSON)
                .build();
        guard.chat(preset);
        dumpSchema("preset-via-json-guard", delegate.lastRequest.get());
    }

    /** 探针 4：@JsonProperty(required = true) 标注后，schema.required 应包含 claims 及 claim 的 abilityName/masteryLevel/evidenceText。 */
    @Test
    void probeRequiredAnnotationLandInSchema() {
        RecordingModel model = new RecordingModel(MINIMAL_JSON);
        EmployeeAbilityAiService service = AiServices.builder(EmployeeAbilityAiService.class)
                .chatModel(model)
                .build();
        try {
            service.extractAbilities("{\"sourceText\":\"probe\"}");
        } catch (Throwable t) {
            System.out.println("[PROBE] call threw: " + t);
        }
        ChatRequest request = model.lastRequest.get();
        if (request == null || request.responseFormat() == null || request.responseFormat().jsonSchema() == null
                || !(request.responseFormat().jsonSchema().rootElement() instanceof JsonObjectSchema root)) {
            System.out.println("[PROBE] no schema generated — required annotation check skipped");
            return;
        }
        System.out.println("[PROBE] root.required = " + root.required());
        if (root.properties().get("claims") instanceof dev.langchain4j.model.chat.request.json.JsonArraySchema claimsArray
                && claimsArray.items() instanceof JsonObjectSchema claimSchema) {
            System.out.println("[PROBE] claims.required = " + claimSchema.required());
        } else {
            System.out.println("[PROBE] claims schema = " + root.properties().get("claims"));
        }
        org.junit.jupiter.api.Assertions.assertTrue(root.required().contains("claims"),
                "claims must be in root required list");
    }
}
