CREATE TABLE IF NOT EXISTS matching_rematch_validation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    closure_business_key VARCHAR(255) NOT NULL,
    original_matching_record_id BIGINT,
    task_id VARCHAR(64),
    new_matching_record_id BIGINT,
    old_score DECIMAL(5,2),
    old_match_status INT,
    new_score DECIMAL(5,2),
    new_match_status INT,
    validation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    fail_reason VARCHAR(500),
    emp_id BIGINT,
    post_id BIGINT,
    tag_id BIGINT,
    created_by BIGINT,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT DEFAULT 0,
    version INT DEFAULT 0,
    UNIQUE KEY uk_closure_record (closure_business_key, original_matching_record_id),
    INDEX idx_emp_post (emp_id, post_id),
    INDEX idx_task_id (task_id)
);
